### ISSUE TITLE
Add contextual processing

### ISSUE THREAD

**Issue by gmaxey** [electric-cloud/EC-DSLIDE#27]
Allow a user to provide a jobStepId context for example so that string expansion and alias will work as if the DSL were being run from that job step.  This would be a very powerful tool for developing DSL steps.

Support:
$[/myJob/jobName]
getProperty("/myJob/jobName").value

This could be accomplished by first running expandString, then evalDsl both with the --jobStepId field provided.

**Comment by imago-storm** [comment]
This issue was moved to electric-cloud-community/EC-DSLIDE#16
