### ISSUE TITLE
Load the entire list of APIs

### ISSUE THREAD

**Issue by gmaxey** [electric-cloud/EC-DSLIDE#35]
Currently, the the command completion and highlighting lists are generated by hand and added to the plugin itself.  It would be better to have this pulled on loading the IDE.  I haven't found the API to get the entire list of APIs yet.

**Comment by gmaxey** [comment]
https://flow/rest/doc/v1.0/api/api-docs

**Comment by gmaxey** [comment]
.done(function(apiResponse) {
		var apis = [];
		for (var api in apiResponse.apis) {
		  apis.push( apiResponse.apis[api].path.replace("/","") )
		}
		return apis;

**Comment by imago-storm** [comment]
This issue was moved to electric-cloud-community/EC-DSLIDE#20
