### ISSUE TITLE
Add Insert-Deploy objects

### ISSUE THREAD

**Issue by gmaxey** [electric-cloud/EC-DSLIDE#40]
- [ ] Insert process.  Include comments to indicate how to set for an application process or component.
- [ ] Insert process step.  Include comments to indicate how to set as an application process or component process step.
- [ ] Insert component.  Include the retrieve step in a comment block.
- [ ] Insert tasks: gate, deploy, plugin, procedure.  Or, at least comments explaining which attributes are needed for each.
- [ ] Insert tier map

**Comment by imago-storm** [comment]
This issue was moved to electric-cloud-community/EC-DSLIDE#22
