### ISSUE TITLE
No way to switch user

### ISSUE THREAD

**Issue by dhubbell** [electric-cloud/EC-DSLIDE#50]
The first time you submit DSL, the page asks for your username and password.  If you have to switch accounts for some reason, like the current account doesn't have access to perform something the DSL requires, there is no way to do so.  Closing the page and reopening reuses the same credentials and the user your are logged in as in Flow, proper, has no bearing on the user being used by the DSL IDE page.  So if you log out of Flow, you are still authenticated in the DSL IDE page with the credentials you originally entered on the page.

**Comment by imago-storm** [comment]
This issue was moved to electric-cloud-community/EC-DSLIDE#2
